openapi: 3.0.3
info:
  title: SageStone API
  version: 1.0.0
paths:
  /v1/tenants:
    get:
      summary: List tenants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'
components:
  schemas:
    Tenant:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
